// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef OI_H
#define OI_H
#include "WPILib.h"
class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Joystick* joy4;
	JoystickButton* indexFwd;
	JoystickButton* injectorBack;
	JoystickButton* injectorFwd;
	JoystickButton* fireButton2;
	JoystickButton* startShooterButton2;
	JoystickButton* articulateDownButton2;
	JoystickButton* articulateUpButton2;
	Joystick* joy3;
	Joystick* joy2;
	JoystickButton* fireButton1;
	JoystickButton* startShooterButton1;
	JoystickButton* articulateDownButton1;
	JoystickButton* articulateUpButton1;
	Joystick* joy1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();
 
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	Joystick* getJoy1();
	Joystick* getJoy2();
	Joystick* getJoy3();
	Joystick* getJoy4();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};
#endif
