// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "DriveBase.h"
#include "../Robotmap.h"
DriveBase::DriveBase() : Subsystem("DriveBase") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	fRController = RobotMap::driveBaseFRController;
	fLController = RobotMap::driveBaseFLController;
	bRController = RobotMap::driveBaseBRController;
	bLController = RobotMap::driveBaseBLController;
	robotDrive41 = RobotMap::driveBaseRobotDrive41;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	robotDrive41->SetInvertedMotor(RobotDrive::kFrontRightMotor, true);
	robotDrive41->SetInvertedMotor(RobotDrive::kRearRightMotor, true);
}
    
void DriveBase::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
void DriveBase::drive(double x, double y, double theta) {
	robotDrive41->MecanumDrive_Cartesian(-x, y, theta, 0);
}
